import './global.css'

import type { Metadata } from "next";
import { lato } from "../utils/fonts";
import { DesktopHeader } from "@/components/Molecules/DesktopHeader/DesktopHeader";
import { Button } from '@/components/Atoms/Button/Button';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <DesktopHeader/>
        {children}
      </body>
    </html>
  );
}
